<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mira-PC" name="com.example.tests.ContactCreationTest" tests="2" failures="0" timestamp="7 Sep 2014 11:15:51 GMT" time="4.651" errors="2">
  <testcase name="testNonEmptyContactCreation" time="1.977" classname="com.example.tests.ContactCreationTest">
    <error type="java.lang.AssertionError" message="
Expected: &lt;[ContactData [firstName=, lastName=testName-1401653762yljnsypojeqxgedtpgdv], ContactData [firstName=testName-1942777357wognrmoqtpuwwkenyscm, lastName=], ContactData [firstName=testName-2107454482qwohykmumwredtthfzut, lastName=testName-253020693rmgagwhahydzeizjchkl], ContactData [firstName=testName408169317cqulossbvzdskoyoikjw, lastName=testName1948549946mtgxezexkjxvetfsjzgt]]&gt;
     but: was &lt;[ContactData [firstName=, lastName=testName-1401653762yljnsypojeqxgedtpgdv], ContactData [firstName=testName-1942777357wognrmoqtpuwwkenyscm, lastName=], ContactData [firstName=testName-253020693rmgagwhahydzeizjchkl, lastName=testName-2107454482qwohykmumwredtthfzut], ContactData [firstName=testName408169317cqulossbvzdskoyoikjw, lastName=testName1948549946mtgxezexkjxvetfsjzgt]]&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: <[ContactData [firstName=, lastName=testName-1401653762yljnsypojeqxgedtpgdv], ContactData [firstName=testName-1942777357wognrmoqtpuwwkenyscm, lastName=], ContactData [firstName=testName-2107454482qwohykmumwredtthfzut, lastName=testName-253020693rmgagwhahydzeizjchkl], ContactData [firstName=testName408169317cqulossbvzdskoyoikjw, lastName=testName1948549946mtgxezexkjxvetfsjzgt]]]]><![CDATA[>
     but: was <[ContactData [firstName=, lastName=testName-1401653762yljnsypojeqxgedtpgdv], ContactData [firstName=testName-1942777357wognrmoqtpuwwkenyscm, lastName=], ContactData [firstName=testName-253020693rmgagwhahydzeizjchkl, lastName=testName-2107454482qwohykmumwredtthfzut], ContactData [firstName=testName408169317cqulossbvzdskoyoikjw, lastName=testName1948549946mtgxezexkjxvetfsjzgt]]]]><![CDATA[>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at com.example.tests.ContactCreationTest.testNonEmptyContactCreation(ContactCreationTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testNonEmptyContactCreation -->
  <testcase name="testNonEmptyContactCreation" time="2.674" classname="com.example.tests.ContactCreationTest">
    <error type="java.lang.AssertionError" message="
Expected: &lt;[ContactData [firstName=testName-1401653762yljnsypojeqxgedtpgdv, lastName=], ContactData [firstName=testName-1942777357wognrmoqtpuwwkenyscm, lastName=], ContactData [firstName=testName408169317cqulossbvzdskoyoikjw, lastName=testName1948549946mtgxezexkjxvetfsjzgt]]&gt;
     but: was &lt;[ContactData [firstName=, lastName=testName-1401653762yljnsypojeqxgedtpgdv], ContactData [firstName=testName-1942777357wognrmoqtpuwwkenyscm, lastName=], ContactData [firstName=testName408169317cqulossbvzdskoyoikjw, lastName=testName1948549946mtgxezexkjxvetfsjzgt]]&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: <[ContactData [firstName=testName-1401653762yljnsypojeqxgedtpgdv, lastName=], ContactData [firstName=testName-1942777357wognrmoqtpuwwkenyscm, lastName=], ContactData [firstName=testName408169317cqulossbvzdskoyoikjw, lastName=testName1948549946mtgxezexkjxvetfsjzgt]]]]><![CDATA[>
     but: was <[ContactData [firstName=, lastName=testName-1401653762yljnsypojeqxgedtpgdv], ContactData [firstName=testName-1942777357wognrmoqtpuwwkenyscm, lastName=], ContactData [firstName=testName408169317cqulossbvzdskoyoikjw, lastName=testName1948549946mtgxezexkjxvetfsjzgt]]]]><![CDATA[>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at com.example.tests.ContactCreationTest.testNonEmptyContactCreation(ContactCreationTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testNonEmptyContactCreation -->
</testsuite> <!-- com.example.tests.ContactCreationTest -->
